---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: auto-instrumentation
  labels: 
    app: otel-auto-instrumentation
spec:
  exporter:
    endpoint: 172.29.92.175:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'
      - name: COLLECTOR_SERVICE_ADDR
        value: "http://172.29.92.175:4318"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://172.29.92.175:4318"
      - name: OTEL_SERVICE_NAME
        value: "recommendationservice"
      - name: ENABLE_TRACING
        value: "1"
      - name: ENABLE_LOGGING
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
  java:
    env:
      - name: COLLECTOR_SERVICE_ADDR
        value: "http://172.29.92.175:4317"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://172.29.92.175:4317"
      - name: OTEL_SERVICE_NAME
        value: "adservice"
      - name: ENABLE_TRACING
        value: "1"
      - name: ENABLE_LOGGING
        value: "1"
      - name: ENABLE_PROFILER
        value: "0"
  